// Package agents 提供 Spec/Dev/Review/Test 四个 Agent 的最小实现.
// 阶段 2 的"真实 stub": 每个 Agent 会真正调用一次 CLI Adapter, 把结果写入
// change 目录下的对应 markdown, 并返回 pass/fail. 阶段 3 再扩展为真实工作.
package agents

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/aswe/aswe/internal/adapter"
	"github.com/aswe/aswe/internal/state"
)

// Agent 所有角色化 Agent 的共同接口.
type Agent interface {
	Stage() state.Stage
	Run(ctx context.Context, in *RunInput) (*RunOutput, error)
}

// RunInput 编排器传给 Agent 的输入.
type RunInput struct {
	ChangeID     string
	WorkspaceDir string
	ChangeDir    string // <workspace>/openspec/changes/<change-id>
	ProjectDir   string // <workspace>/projects/<change-id> 代码落盘目录
	ProposalPath string
	PrevOutputs  map[state.Stage]string // 前序节点的 summary

	// --- 方案阶段循环 (plan <-> plan-review) ---
	PlanIteration int    // 第几轮, 从 1 起计
	PlanFeedback  string // 上一轮 plan-review 的改进意见; Plan-Agent 必须参考

	// --- 代码阶段循环 (dev <-> review/test) ---
	CodeIteration  int    // 第几轮, 从 1 起计
	ReviewFeedback string // 上一轮 code-review 的意见; Dev-Agent 必须参考
	TestFeedback   string // 上一轮 test 的失败信息; Dev-Agent 必须修复
}

// RunOutput Agent 的执行结果.
type RunOutput struct {
	Stage      state.Stage
	Passed     bool   // review/test 使用; spec/dev 始终 true
	Adapter    string // 实际使用的适配器名
	Summary    string // 落盘后的 markdown 摘要
	OutputPath string // 产物路径
	Raw        string // AI 原始回复(调试用)
}

// base 所有 agent 共享的部分.
type base struct {
	stage   state.Stage
	cli     adapter.CLIAdapter
	fileOut string // 产物文件名 (相对 ChangeDir)
}

func (b *base) Stage() state.Stage { return b.stage }

func (b *base) invoke(ctx context.Context, in *RunInput, prompt string) (*RunOutput, string, error) {
	return b.invokeWith(ctx, in, prompt, in.WorkspaceDir, 300)
}

// invokeWith 允许自定义工作目录和超时, 用于 Dev/Test 的"真跑".
func (b *base) invokeWith(ctx context.Context, in *RunInput, prompt, workDir string, timeoutSec int) (*RunOutput, string, error) {
	if workDir == "" {
		workDir = in.WorkspaceDir
	}
	if timeoutSec <= 0 {
		timeoutSec = 300
	}
	resp, err := b.cli.Invoke(ctx, adapter.Request{
		Prompt:         prompt,
		WorkDir:        workDir,
		Mode:           adapter.ModeHeadless,
		TimeoutSeconds: timeoutSec,
	})
	if err != nil {
		return nil, "", err
	}
	outPath := filepath.Join(in.ChangeDir, b.fileOut)
	header := fmt.Sprintf("<!-- generated by aswe %s agent at %s via %s -->\n\n",
		b.stage, time.Now().Format(time.RFC3339), resp.Adapter)
	if err := os.WriteFile(outPath, []byte(header+resp.Output+"\n"), 0o644); err != nil {
		return nil, "", err
	}
	return &RunOutput{
		Stage:      b.stage,
		Adapter:    resp.Adapter,
		OutputPath: outPath,
		Raw:        resp.Output,
	}, resp.Output, nil
}

// readIfExists 读取文件, 不存在返回空串.
func readIfExists(p string) string {
	if p == "" {
		return ""
	}
	data, err := os.ReadFile(p)
	if err != nil {
		return ""
	}
	return string(data)
}

// parseVerdict 从 AI 输出中解析 PASS/FAIL.
// 解析规则(健壮版):
//  1. 从后往前扫描**所有行**, 找到第一条包含 "VERDICT:" 的行, 根据其中是否出现 PASS/FAIL 判定.
//     - 允许 markdown 加粗/引用等前后缀 (例如 "**VERDICT: FAIL**", "> VERDICT: PASS").
//     - 同一行同时出现 FAIL 和 PASS 时, 以 FAIL 优先 (安全策略).
//  2. 若全文没有 VERDICT: 行, 再兜底看是否有裸 "PASS" / "FAIL" 单行.
//  3. 都找不到时, 为避免把带阻塞的 review 误判为通过, **缺省返回 false (FAIL)**,
//     交给上层循环再跑一轮或让用户介入.
func parseVerdict(s string) bool {
	lines := strings.Split(strings.TrimSpace(s), "\n")

	// pass 1: 反向找 VERDICT: 关键字, 任意位置都可以
	for i := len(lines) - 1; i >= 0; i-- {
		u := strings.ToUpper(strings.TrimSpace(lines[i]))
		if u == "" {
			continue
		}
		if strings.Contains(u, "VERDICT:") {
			if strings.Contains(u, "FAIL") {
				return false
			}
			if strings.Contains(u, "PASS") {
				return true
			}
			// VERDICT: 存在但既没 PASS 也没 FAIL, 当作未判定, 继续往前找
		}
	}

	// pass 2: 没找到 VERDICT 行, 兜底看是否有裸 PASS / FAIL 单行 (反向优先取离结尾最近的)
	for i := len(lines) - 1; i >= 0; i-- {
		u := strings.ToUpper(strings.TrimSpace(lines[i]))
		switch u {
		case "PASS", "**PASS**":
			return true
		case "FAIL", "**FAIL**":
			return false
		}
	}

	// 都找不到时 -> 视为 FAIL, 避免把问题评审静默放行
	return false
}
