// Package agents 的"单元化"版本 Dev/Review/Test.
//
// 与旧版一把梭的 Dev/Review/Test 不同, 这里每次只针对一个 Unit 执行:
//   - 产物写入 <ArtifactDir>/units/<unit-id>/{dev,review,test}.md, 不覆盖旧单元
//   - prompt 里明确约束本轮只处理该 Unit 的 scope (软约束, 跨单元改动需在报告里声明)
package agents

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"github.com/aswe/aswe/internal/adapter"
	"github.com/aswe/aswe/internal/state"
)

// UnitInput 针对单元的执行输入. 与 RunInput 区别在于多了 Module/Unit 上下文.
type UnitInput struct {
	ChangeID     string
	WorkspaceDir string
	ChangeDir    string
	ArtifactDir  string
	ProjectDir   string

	Spec string // spec.md 全文 (给 AI 作上下文)
	Plan string // plan.md 全文 (给 AI 作上下文)

	Module *state.Module
	Unit   *state.Unit

	// Unit 自己的循环次数 (从 0 起, 第 N 次重跑时 = N)
	Iteration int

	// 上一轮的反馈: review 打回时 ReviewFeedback 非空; test 失败时 TestFeedback 非空.
	// Dev-Unit Agent 必须据此修复.
	ReviewFeedback string
	TestFeedback   string
}

// UnitOutput 单元级 Agent 的结果.
type UnitOutput struct {
	Passed     bool
	Adapter    string
	Summary    string
	OutputPath string
	Raw        string
}

// UnitAgent 单元粒度的角色接口.
type UnitAgent interface {
	Stage() state.Stage
	RunUnit(ctx context.Context, in *UnitInput) (*UnitOutput, error)
}

// --- 共享工具 ---

// unitIDRE 单元 ID 的合法字符集 (Plan-Agent 输出): 字母数字 + . _ -.
// 任何其它字符(空格/路径分隔符/中文/..) 都视为违例, 避免 AI 写出 "../etc" 之类
// 路径穿越 ID 把 dev.md 写到 ArtifactDir 之外.
var unitIDRE = regexp.MustCompile(`^[A-Za-z0-9._-]+$`)

// sanitizeUnitID 校验 ID 仅包含安全字符且没有 .. 等穿越前缀, 不合法则返回 error.
func sanitizeUnitID(unitID string) (string, error) {
	id := strings.TrimSpace(unitID)
	if id == "" {
		return "", fmt.Errorf("unit id 为空")
	}
	if !unitIDRE.MatchString(id) {
		return "", fmt.Errorf("unit id %q 含非法字符 (仅允许 [A-Za-z0-9._-])", unitID)
	}
	if id == "." || id == ".." || strings.Contains(id, "..") {
		return "", fmt.Errorf("unit id %q 含路径穿越片段", unitID)
	}
	return id, nil
}

// unitDir 返回 <ArtifactDir>/units/<unit-id>/, 不存在则创建.
func unitDir(artifactDir, unitID string) (string, error) {
	safe, err := sanitizeUnitID(unitID)
	if err != nil {
		return "", err
	}
	dir := filepath.Join(artifactDir, "units", safe)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}
	return dir, nil
}

// invokeUnit 统一调用 CLI + 写产物.
func invokeUnit(ctx context.Context, cli adapter.CLIAdapter, stage state.Stage,
	in *UnitInput, prompt, workDir, fileName string, timeoutSec int,
) (*UnitOutput, error) {
	if workDir == "" {
		workDir = in.WorkspaceDir
	}
	if timeoutSec <= 0 {
		timeoutSec = 600
	}
	resp, err := cli.Invoke(ctx, adapter.Request{
		Prompt:         prompt,
		WorkDir:        workDir,
		Mode:           adapter.ModeHeadless,
		TimeoutSeconds: timeoutSec,
	})
	if err != nil {
		return nil, err
	}
	artifactDir := in.ArtifactDir
	if artifactDir == "" {
		artifactDir = in.ChangeDir
	}
	dir, err := unitDir(artifactDir, in.Unit.ID)
	if err != nil {
		return nil, err
	}
	out := filepath.Join(dir, fileName)
	header := fmt.Sprintf("<!-- generated by aswe %s agent for unit %s iter=%d at %s via %s -->\n\n",
		stage, in.Unit.ID, in.Iteration, time.Now().Format(time.RFC3339), resp.Adapter)
	if err := os.WriteFile(out, []byte(header+resp.Output+"\n"), 0o644); err != nil {
		return nil, err
	}
	return &UnitOutput{
		Passed:     parseVerdict(resp.Output),
		Adapter:    resp.Adapter,
		Summary:    firstLines(resp.Output, 12),
		OutputPath: out,
		Raw:        resp.Output,
	}, nil
}

// ==================================================================
// Dev-Unit Agent
// ==================================================================

type DevUnitAgent struct{ cli adapter.CLIAdapter }

func NewDevUnit(cli adapter.CLIAdapter) *DevUnitAgent { return &DevUnitAgent{cli: cli} }
func (a *DevUnitAgent) Stage() state.Stage            { return state.StageDev }

func (a *DevUnitAgent) RunUnit(ctx context.Context, in *UnitInput) (*UnitOutput, error) {
	if in.ProjectDir == "" {
		return nil, fmt.Errorf("DevUnitAgent: ProjectDir 未配置")
	}
	if err := os.MkdirAll(in.ProjectDir, 0o755); err != nil {
		return nil, err
	}
	tree := listProjectTree(in.ProjectDir, 5)

	var feedback strings.Builder
	if strings.TrimSpace(in.ReviewFeedback) != "" {
		fmt.Fprintf(&feedback, "\n【上一轮 Code-Review 反馈, 必须逐条解决】\n----\n%s\n----\n", in.ReviewFeedback)
	}
	if strings.TrimSpace(in.TestFeedback) != "" {
		fmt.Fprintf(&feedback, "\n【上一轮 Test 失败信息, 必须修复】\n----\n%s\n----\n", in.TestFeedback)
	}

	iterBadge := ""
	if in.Iteration > 0 {
		iterBadge = fmt.Sprintf(" (第 %d 轮修复)", in.Iteration)
	}

	body := fmt.Sprintf(`你是 Dev-Agent, 本轮**只负责一个单元**%s.

== 当前单元 ==
模块: %s — %s
单元 ID: %s
标题: %s
负责范围 (scope): %s
交付物 (deliverable): %s

== 软约束 ==
- **优先只修改本单元 scope 内的文件**; 如确需跨单元改动(例如要修改公共入口/索引), 在
  dev.md 里用 "## 跨单元改动" 章节**显式列出文件并给理由**.
- 不要抢做其他单元的工作; 其他单元会由独立的 Dev 轮次处理.
- 新增依赖仍需写进项目级依赖清单, 禁止全局安装.

spec (需求真源, 仅作背景):
----
%s
----

plan.md (本单元相关章节, 完整方案见 %s/plan.md):
----
%s
----
%s
当前项目目录已有文件:
----
%s
----

输出 (**这份 dev.md 报告必须通过 stdout 返回**, 不要把它当成文件用 Write 写到磁盘 — aswe 会自行落盘; 但本单元的项目代码/测试文件应当照常用 Write 写入 ProjectDir):
- "## 实现摘要" : 本轮为单元 %s 做了什么.
- "## 变更文件清单" : "- path — 说明".
- "## 跨单元改动" : 没有就写"无".
- "## 如何本地验证" : 简述.
- "## 需要人类批准" : 按 NEEDS_HUMAN_APPROVAL: 开头列出要人批准的命令; 没有就写"无".
- 末尾单独一行: 完成且无阻塞 -> VERDICT: PASS; 否则 VERDICT: FAIL`,
		iterBadge, in.Module.ID, in.Module.Title,
		in.Unit.ID, in.Unit.Title, in.Unit.Scope, in.Unit.Deliverable,
		clipRunes(in.Spec, 3000),
		in.ArtifactDir, summarizePlanForUnit(in.Plan, in.Module.ID, 4000),
		feedback.String(), tree, in.Unit.ID)

	prompt := withSafety(in.ProjectDir, safetyRulesForActor, body)
	return invokeUnit(ctx, a.cli, state.StageDev, in, prompt, in.ProjectDir, "dev.md", 1200)
}

// ==================================================================
// Review-Unit Agent
// ==================================================================

type ReviewUnitAgent struct{ cli adapter.CLIAdapter }

func NewReviewUnit(cli adapter.CLIAdapter) *ReviewUnitAgent { return &ReviewUnitAgent{cli: cli} }
func (a *ReviewUnitAgent) Stage() state.Stage               { return state.StageReview }

func (a *ReviewUnitAgent) RunUnit(ctx context.Context, in *UnitInput) (*UnitOutput, error) {
	tree := listProjectTree(in.ProjectDir, 6)
	devReport := readUnitArtifact(in.ArtifactDir, in.ChangeDir, in.Unit.ID, "dev.md")

	body := fmt.Sprintf(`你是 Code-Review-Agent, 对**单元 %s** 的本轮 Dev 产出做审查.
只读不改. 结论仅覆盖本单元的 scope; 其他单元会由独立的 review 轮次审查.

模块: %s — %s
单元 scope: %s
单元交付物: %s

spec (背景, 已截断):
----
%s
----

plan.md (本单元相关章节):
----
%s
----

本单元 dev 报告:
----
%s
----

项目目录树:
----
%s
----

输出要求 (**markdown 必须通过 stdout 返回**, 不要用 Write 工具落盘 review.md):
- "## 结论" : 一句话是否通过.
- "## 对交付物的覆盖" : 交付物是否按承诺实现, 引用文件:行号或文件:函数.
- "## 对 scope 的符合度" : 是否主要改动在 scope 内; 跨单元改动是否合理.
- "## 问题清单" : 严重度(阻塞/建议), 文件位置, 修复建议.
- "## 给 Dev 的反馈" : 仅 FAIL 时填; 每条指向文件/函数并给出怎么改.
- 末尾单独一行:
	- 有阻塞级问题或交付物未实现 -> VERDICT: FAIL
	- 否则 -> VERDICT: PASS`,
		in.Unit.ID, in.Module.ID, in.Module.Title,
		in.Unit.Scope, in.Unit.Deliverable,
		clipRunes(in.Spec, 2000),
		summarizePlanForUnit(in.Plan, in.Module.ID, 3000),
		devReport, tree)

	prompt := withSafety(in.ProjectDir, safetyRulesForReader, body)
	return invokeUnit(ctx, a.cli, state.StageReview, in, prompt, in.ProjectDir, "review.md", 600)
}

// ==================================================================
// Test-Unit Agent
// ==================================================================

type TestUnitAgent struct{ cli adapter.CLIAdapter }

func NewTestUnit(cli adapter.CLIAdapter) *TestUnitAgent { return &TestUnitAgent{cli: cli} }
func (a *TestUnitAgent) Stage() state.Stage             { return state.StageTest }

func (a *TestUnitAgent) RunUnit(ctx context.Context, in *UnitInput) (*UnitOutput, error) {
	tree := listProjectTree(in.ProjectDir, 6)
	devReport := readUnitArtifact(in.ArtifactDir, in.ChangeDir, in.Unit.ID, "dev.md")
	kind := detectProjectKind(in.ProjectDir)

	var strategy string
	timeoutSec := 900
	switch kind {
	case "go":
		strategy = `【项目类型: Go】仅用项目已有测试栈: "go test ./... -run <相关>". 无 _test.go 则就地新增 1-2 个覆盖本单元交付物.`
	case "node":
		strategy = `【项目类型: Node.js】优先已声明的 test script; 禁止新增测试框架; 可用 node:test + node:assert 写轻量测试覆盖本单元交付物.`
	case "python":
		strategy = `【项目类型: Python】只用已声明测试栈; 或用 unittest; 禁止 pip install 新包.`
	case "static":
		timeoutSec = 300
		strategy = `【项目类型: 静态前端】禁止 npm/pip/安装操作. 做: 1) 文件结构检查 2) node --check 语法检查 3) 对本单元涉及的纯函数抽取为 *.test.mjs 用 node:test 断言 4) 其他 spec 场景给"手工验证步骤".`
	default:
		timeoutSec = 300
		strategy = `【未识别类型】只做轻量静态自检: 列文件 + 语法检查 + 手工验证步骤.`
	}

	body := fmt.Sprintf(`你是 Test-Agent, 对**单元 %s** 的本轮交付做针对性验证.
只在 %s 内操作, 禁止 sudo/全局安装.

%s

模块: %s — %s
单元 scope: %s
单元交付物: %s

spec (背景, 已截断):
----
%s
----

本单元 dev 报告:
----
%s
----

项目目录树:
----
%s
----

输出 (**markdown 必须通过 stdout 返回**, 不要用 Write 落盘 test.md; 真要新增的测试文件本身则用 Write 写到 ProjectDir):
- "## 项目类型识别" : 一句话.
- "## 执行的验证命令" : 每条一行.
- "## 结果摘要" : 通过/失败/跳过 数量.
- "## 失败详情" : 失败时贴真实输出.
- "## 手工验证用例" : 静态/未识别类型填.
- "## 给 Dev 的反馈" : FAIL 时填.
- 末尾单独一行: 全通过 -> VERDICT: PASS; 硬失败 -> VERDICT: FAIL.`,
		in.Unit.ID, in.ProjectDir, strategy,
		in.Module.ID, in.Module.Title,
		in.Unit.Scope, in.Unit.Deliverable,
		clipRunes(in.Spec, 2000), devReport, tree)

	prompt := withSafety(in.ProjectDir, safetyRulesForActor, body)
	return invokeUnit(ctx, a.cli, state.StageTest, in, prompt, in.ProjectDir, "test.md", timeoutSec)
}

// readUnitArtifact 读取单元产物文件 (dev.md/review.md/test.md).
// 非法 unit id 返回空串, 不报错, 上层使用方会按"无反馈"处理.
func readUnitArtifact(artifactDir, legacyChangeDir, unitID, name string) string {
	safe, err := sanitizeUnitID(unitID)
	if err != nil {
		return ""
	}
	for _, dir := range []string{artifactDir, legacyChangeDir} {
		if dir == "" {
			continue
		}
		p := filepath.Join(dir, "units", safe, name)
		data, err := os.ReadFile(p)
		if err == nil {
			return string(data)
		}
	}
	return ""
}

// summarizePlanForUnit 为单元 prompt 生成 plan.md 的"瘦身版":
//   - 摘要前导段(plan.md 顶部到第一个 H2 之间), 仅取最多 maxRunes 字.
//   - 找到"## 模块 <id>"或包含 unit 所属 module ID 的 H2 章节, 截到下一个 H2/H1 为止.
//
// 这样 Dev/Review/Test 的 prompt 不再每轮都被 plan 全文淹没,
// 模型注意力会被自然地拉到与本单元相关的方案章节. 找不到 module 相关章节就退化为整篇.
func summarizePlanForUnit(plan, moduleID string, maxRunes int) string {
	if plan == "" {
		return ""
	}
	if maxRunes <= 0 {
		maxRunes = 4000
	}
	lines := strings.Split(plan, "\n")
	prefaceEnd := -1 // 第一个 H1/H2 出现的位置, 用作"前导段"边界
	moduleStart := -1
	for i, ln := range lines {
		t := strings.TrimSpace(ln)
		isHeading := strings.HasPrefix(t, "## ") || strings.HasPrefix(t, "# ")
		if isHeading && prefaceEnd < 0 {
			prefaceEnd = i
		}
		if strings.HasPrefix(t, "## ") {
			tit := strings.ToLower(strings.TrimPrefix(t, "## "))
			if strings.Contains(tit, strings.ToLower(moduleID)) {
				moduleStart = i
				break
			}
		}
	}
	var preface []string
	if prefaceEnd > 0 {
		preface = lines[:prefaceEnd]
	}
	if moduleStart < 0 {
		// 找不到对应模块章节, 退回原文; 由调用方决定是否再做整体截断.
		return plan
	}
	end := len(lines)
	for j := moduleStart + 1; j < len(lines); j++ {
		t := strings.TrimSpace(lines[j])
		if strings.HasPrefix(t, "## ") || strings.HasPrefix(t, "# ") {
			end = j
			break
		}
	}
	prefStr := strings.TrimSpace(strings.Join(preface, "\n"))
	prefStr = clipRunes(prefStr, maxRunes/2)
	modStr := strings.TrimSpace(strings.Join(lines[moduleStart:end], "\n"))
	modStr = clipRunes(modStr, maxRunes)
	if prefStr == "" {
		return modStr
	}
	return prefStr + "\n\n" + modStr
}

// clipRunes 按 rune 截断, 超出长度时追加省略提示.
func clipRunes(s string, n int) string {
	if n <= 0 {
		return ""
	}
	rs := []rune(s)
	if len(rs) <= n {
		return s
	}
	return string(rs[:n]) + "\n…(已截断)"
}

// ExtractFeedbackSection 从 review.md / test.md 这种 markdown 中, 提取"## 给 Dev 的反馈"
// 这种 H2 章节的纯文本(不含标题行), 截到下一个 H1/H2 或 "VERDICT:" 行为止.
// 这样下一轮 Dev/Unit 收到的 prompt 不会被整张报告(头注释/项目目录树/spec 全文等)淹没,
// 既省 token 也让模型的注意力聚焦在真正要修复的问题上.
//
// 找不到该 section 时退化为返回原文, 由调用方决定要不要额外裁剪.
func ExtractFeedbackSection(md, headerText string) string {
	if md == "" {
		return ""
	}
	lines := strings.Split(md, "\n")
	headerNorm := strings.ToLower(strings.TrimSpace(headerText))
	startIdx := -1
	for i, ln := range lines {
		t := strings.TrimSpace(ln)
		if strings.HasPrefix(t, "## ") {
			cur := strings.ToLower(strings.TrimSpace(strings.TrimPrefix(t, "## ")))
			if strings.Contains(cur, headerNorm) {
				startIdx = i + 1
				break
			}
		}
	}
	if startIdx < 0 {
		return strings.TrimSpace(md)
	}
	end := len(lines)
	for j := startIdx; j < len(lines); j++ {
		t := strings.TrimSpace(lines[j])
		if strings.HasPrefix(t, "## ") || strings.HasPrefix(t, "# ") || strings.HasPrefix(t, "VERDICT:") {
			end = j
			break
		}
	}
	return strings.TrimSpace(strings.Join(lines[startIdx:end], "\n"))
}
